services:
  - type: web
    name: ai-recruitment-services
    env: python
    region: oregon
    plan: free
    buildCommand: "cd services && pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "cd services && uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1"
    healthCheckPath: "/health"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: PYTHONPATH
        value: /opt/render/project/src/services
